#Testing
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: deploy01
  name: deploy01
spec:
  replicas: 1
  selector:
    matchLabels:
      run: deploy01
  template:
    metadata:
      labels:
        run: deploy01
    spec:
      containers:
      - image: kiran2361993/rollingupdate:v10
        name: deploy01
